# Generated by Django 5.2.1 on 2025-05-26 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('barcode_image', models.ImageField(blank=True, upload_to='barcodes/')),
            ],
        ),
    ]
