# Generated by Django 5.2.1 on 2025-05-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='barcode_image',
            new_name='qr_image',
        ),
    ]
