# Generated by Django 5.2.1 on 2025-06-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_rename_barcode_image_participant_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
