# Generated by Django 5.2.1 on 2025-05-31 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_rename_barcode_image_participant_qr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField()),
                ('age_group', models.CharField(choices=[('6-9', '6-9'), ('10-13', '10-13'), ('14-18', '14-18')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='points',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GameCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
            options={
                'unique_together': {('participant', 'game')},
            },
        ),
    ]
