# Generated by Django 5.2.1 on 2025-05-31 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_game_remove_participant_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GamePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')])),
                ('points_awarded', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='participants.game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
            options={
                'unique_together': {('participant', 'game')},
            },
        ),
    ]
