# Generated by Django 5.2.1 on 2025-06-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participant_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_group', models.CharField(choices=[('6-9', '6-9'), ('10-13', '10-13'), ('14-18', '14-18')], max_length=10)),
            ],
        ),
    ]
