# Generated by Django 5.2.1 on 2025-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_game_is_ranked_gameplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='points',
        ),
        migrations.AddField(
            model_name='game',
            name='first_place_points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='second_place_points',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='game',
            name='third_place_points',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gamecompletion',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], null=True),
        ),
    ]
