# Generated by Django 5.2.1 on 2025-06-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_group',
            field=models.CharField(max_length=10),
        ),
    ]
