# Generated by Django 5.2.1 on 2025-06-01 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_game_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_group',
            field=models.CharField(choices=[('6-9', '6-9'), ('10-13', '10-13'), ('14-18', '14-18')], max_length=10),
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
            options={
                'unique_together': {('participant', 'game')},
            },
        ),
    ]
